
package proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FileImplService", targetNamespace = "http://s19358/mtom", wsdlLocation = "http://localhost:8080/mtom?wsdl")
public class FileImplService
    extends Service
{

    private final static URL FILEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException FILEIMPLSERVICE_EXCEPTION;
    private final static QName FILEIMPLSERVICE_QNAME = new QName("http://s19358/mtom", "FileImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/mtom?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FILEIMPLSERVICE_WSDL_LOCATION = url;
        FILEIMPLSERVICE_EXCEPTION = e;
    }

    public FileImplService() {
        super(__getWsdlLocation(), FILEIMPLSERVICE_QNAME);
    }

    public FileImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FILEIMPLSERVICE_QNAME, features);
    }

    public FileImplService(URL wsdlLocation) {
        super(wsdlLocation, FILEIMPLSERVICE_QNAME);
    }

    public FileImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FILEIMPLSERVICE_QNAME, features);
    }

    public FileImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FileImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IFile
     */
    @WebEndpoint(name = "IFilePort")
    public IFile getIFilePort() {
        return super.getPort(new QName("http://s19358/mtom", "IFilePort"), IFile.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IFile
     */
    @WebEndpoint(name = "IFilePort")
    public IFile getIFilePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://s19358/mtom", "IFilePort"), IFile.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FILEIMPLSERVICE_EXCEPTION!= null) {
            throw FILEIMPLSERVICE_EXCEPTION;
        }
        return FILEIMPLSERVICE_WSDL_LOCATION;
    }

}
