
package client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FilterImpl", targetNamespace = "http://implementation/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FilterImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<client.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "filterBirthDate", targetNamespace = "http://implementation/", className = "client.FilterBirthDate")
    @ResponseWrapper(localName = "filterBirthDateResponse", targetNamespace = "http://implementation/", className = "client.FilterBirthDateResponse")
    @Action(input = "http://implementation/FilterImpl/filterBirthDateRequest", output = "http://implementation/FilterImpl/filterBirthDateResponse")
    public List<Person> filterBirthDate(
        @WebParam(name = "arg0", targetNamespace = "")
        XMLGregorianCalendar arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<client.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "filterSurname", targetNamespace = "http://implementation/", className = "client.FilterSurname")
    @ResponseWrapper(localName = "filterSurnameResponse", targetNamespace = "http://implementation/", className = "client.FilterSurnameResponse")
    @Action(input = "http://implementation/FilterImpl/filterSurnameRequest", output = "http://implementation/FilterImpl/filterSurnameResponse")
    public List<Person> filterSurname(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
